name: Build and Publish Artifact

on:
  push:
    branches:
      - master # Triggers on pushes to the master branch

jobs:
  build-and-publish-artifact:
    runs-on: windows-2025 # Must use Windows for .NET Framework and MSBuild

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      # Step 3: Build the project in Release mode using MSBuild
      - name: Build with MSBuild
        run: msbuild GhidraZipCleaner.sln /p:Configuration=Release /p:Platform="Any CPU"

      # Step 4: Upload the ZIP as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GhidraZipCleaner
          path: ./GhidraZipCleaner/bin/Release